### ISSUE TITLE
Cleanup MDC properties after message processing is completed

### ISSUE THREAD

**Issue by tomazic89** [iris-events/iris#216]
## Description
When processing a message which does not contain headers used in MDC enrichment (see [MDCEnricher.java#L20-L25](https://github.com/iris-events/iris/blob/fc53350b03ce85088cd9e795b23a40bb93f2567a/common/src/main/java/org/iris_events/common/MDCEnricher.java#L20-L25)) logs within current thread will contain MDC properties from previous message.
## Expected Behavior
Logs for current message should contain only MDC properties available for current message taken from message headers.

## Actual Behavior
Logs for current message contain MDC properties of previously processed message when new message does not (re)set all the properties which previous message set.

## Steps to Reproduce the Problem

  1. Consume message with [userId](https://github.com/iris-events/iris/blob/fc53350b03ce85088cd9e795b23a40bb93f2567a/common/src/main/java/org/iris_events/common/MDCProperties.java#L5) header set.
  1. Consume message without [userId](https://github.com/iris-events/iris/blob/fc53350b03ce85088cd9e795b23a40bb93f2567a/common/src/main/java/org/iris_events/common/MDCProperties.java#L5) header set.
  1. Log a message

## Specifications

  - Version: [v6.0.4](https://github.com/iris-events/iris/releases/tag/v6.0.4)

**Comment by gasper-vrhovsek** [comment]
https://github.com/iris-events/iris/pull/220

**Comment by gasper-vrhovsek** [comment]
Closing, this was fixed in #220
